# Generated by Django 4.2.6 on 2023-11-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('launch_year', models.IntegerField()),
                ('specific_impulse', models.FloatField()),
                ('thrust', models.FloatField()),
                ('mass', models.FloatField()),
                ('burn_time', models.FloatField()),
                ('propellant', models.CharField(max_length=255)),
                ('poster_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sucessfull_static_tests', models.IntegerField(default=0)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.motor')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
