# Generated by Django 4.2.6 on 2023-11-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='motor_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='rocket',
            field=models.CharField(max_length=255),
        ),
    ]
