# Generated by Django 4.2.6 on 2023-11-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_remove_motor_poster_url_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='motor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.motor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rocket',
            name='motor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.motor'),
        ),
    ]
