# Generated by Django 4.2.6 on 2023-11-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0004_comment_motor_alter_rocket_motor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='autor',
            new_name='author',
        ),
    ]
