# Generated by Django 4.2.6 on 2023-11-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='motor',
            new_name='motors',
        ),
    ]
